PRODUCT_COPY_FILES += \
    vendor/arise/numbers/ARISE_Version.prop:system/ARISE_Version.prop \
    vendor/arise/numbers/su.d/dts_configurator_wrapper:system/su.d/dts_configurator_wrapper \
    vendor/arise/numbers/su.d/arisesound_setprop:system/su.d/arisesound_setprop \
    vendor/arise/numbers/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
    vendor/arise/numbers/lib/soundfx/libswdax.so:system/lib/soundfx/libswdax.so \
    vendor/arise/numbers/lib/soundfx/libsrs.so:system/lib/soundfx/libsrs.so \
    vendor/arise/numbers/lib/soundfx/libspectrum.so:system/lib/soundfx/libspectrum.so \
    vendor/arise/numbers/lib/soundfx/libsonysweffect.so:system/lib/soundfx/libsonysweffect.so \
    vendor/arise/numbers/lib/soundfx/libsonypostprocbundle.so:system/lib/soundfx/libsonypostprocbundle.so \
    vendor/arise/numbers/lib/soundfx/libqcompostprocbundle.so:system/lib/soundfx/libqcompostprocbundle.so \
    vendor/arise/numbers/lib/soundfx/libmmieffectswrapper.so:system/lib/soundfx/libmmieffectswrapper.so \
    vendor/arise/numbers/lib/soundfx/libmaxxeffect-cembedded.so:system/lib/soundfx/libmaxxeffect-cembedded.so \
    vendor/arise/numbers/lib/soundfx/libmaxv.so:system/lib/soundfx/libmaxv.so \
    vendor/arise/numbers/lib/soundfx/libicepower.so:system/lib/soundfx/libicepower.so \
    vendor/arise/numbers/lib/soundfx/libhpx.so:system/lib/soundfx/libhpx.so \
    vendor/arise/numbers/lib/soundfx/libeffectproxy.so:system/lib/soundfx/libeffectproxy.so \
    vendor/arise/numbers/lib/soundfx/libeagle.so:system/lib/soundfx/libeagle.so \
    vendor/arise/numbers/lib/soundfx/libbbesonicmax.so:system/lib/soundfx/libbbesonicmax.so \
    vendor/arise/numbers/lib/soundfx/libAuro.so:system/lib/soundfx/libAuro.so \
    vendor/arise/numbers/lib/libswsprocessing.so:system/lib/libswsprocessing.so \
    vendor/arise/numbers/lib/libswresample-2.so:system/lib/libswresample-2.so \
    vendor/arise/numbers/lib/libstlport_shared.so:system/lib/libstlport_shared.so \
    vendor/arise/numbers/lib/libstagefright_soft_dtsdec.so:system/lib/libstagefright_soft_dtsdec.so \
    vendor/arise/numbers/lib/libstagefright_soft_dsddec.so:system/lib/libstagefright_soft_dsddec.so \
    vendor/arise/numbers/lib/libstagefright_soft_ddpdec.so:system/lib/libstagefright_soft_ddpdec.so \
    vendor/arise/numbers/lib/libSpectrum_jni.so:system/lib/libSpectrum_jni.so \
    vendor/arise/numbers/lib/libSpectrum.so:system/lib/libSpectrum.so \
    vendor/arise/numbers/lib/libradsone-shared.so:system/lib/libradsone-shared.so \
    vendor/arise/numbers/lib/libosl-maxxaudio-itf.so:system/lib/libosl-maxxaudio-itf.so \
    vendor/arise/numbers/lib/libneutronmp.so:system/lib/libneutronmp.so \
    vendor/arise/numbers/lib/libmaxxeffectwrapper.so:system/lib/libmaxxeffectwrapper.so \
    vendor/arise/numbers/lib/libMAM2-wavesfx-Coretex_A9.so:system/lib/libMAM2-wavesfx-Coretex_A9.so \
    vendor/arise/numbers/lib/libMAM2-processcode-Coretex_A9.so:system/lib/libMAM2-processcode-Coretex_A9.so \
    vendor/arise/numbers/lib/libldacBT_enc.so:system/lib/libldacBT_enc.so \
    vendor/arise/numbers/lib/libiauxusb.so:system/lib/libiauxusb.so \
    vendor/arise/numbers/lib/libiauxsfx_64.so:system/lib/libiauxsfx_64.so \
    vendor/arise/numbers/lib/libiauxsfx.so:system/lib/libiauxsfx.so \
    vendor/arise/numbers/lib/libiauxmpeg_64.so:system/lib/libiauxmpeg_64.so \
    vendor/arise/numbers/lib/libiauxmpeg.so:system/lib/libiauxmpeg.so \
    vendor/arise/numbers/lib/libiauxcodec.so:system/lib/libiauxcodec.so \
    vendor/arise/numbers/lib/libhpx-lite-sdk.so:system/lib/libhpx-lite-sdk.so \
    vendor/arise/numbers/lib/libharman.so:system/lib/libharman.so \
    vendor/arise/numbers/lib/libgnustl_shared.so:system/lib/libgnustl_shared.so \
    vendor/arise/numbers/lib/libgnsdk_dsp.3.09.0.so:system/lib/libgnsdk_dsp.3.09.0.so \
    vendor/arise/numbers/lib/libdts_hpx_service_c.so:system/lib/libdts_hpx_service_c.so \
    vendor/arise/numbers/lib/libdts-dcc-jni-v2.so:system/lib/libdts-dcc-jni-v2.so \
    vendor/arise/numbers/lib/libdts_dca.so:system/lib/libdts_dca.so \
    vendor/arise/numbers/lib/libdtscs.so:system/lib/libdtscs.so \
    vendor/arise/numbers/lib/libdts.so:system/lib/libdts.so \
    vendor/arise/numbers/lib/libDoreso.so:system/lib/libDoreso.so \
    vendor/arise/numbers/lib/libdlbdapstorage.so:system/lib/libdlbdapstorage.so \
    vendor/arise/numbers/lib/libcmxearfx.so:system/lib/libcmxearfx.so \
    vendor/arise/numbers/lib/libavutil-55.so:system/lib/libavutil-55.so \
    vendor/arise/numbers/lib/libavformat-57.so:system/lib/libavformat-57.so \
    vendor/arise/numbers/lib/libavcodec-57.so:system/lib/libavcodec-57.so \
    vendor/arise/numbers/lib/libauvorbis.so:system/lib/libauvorbis.so \
    vendor/arise/numbers/lib/libauusb.so:system/lib/libauusb.so \
    vendor/arise/numbers/lib/libautaglib.so:system/lib/libautaglib.so \
    vendor/arise/numbers/lib/libausoxr.so:system/lib/libausoxr.so \
    vendor/arise/numbers/lib/libausndfile.so:system/lib/libausndfile.so \
    vendor/arise/numbers/lib/libauogg.so:system/lib/libauogg.so \
    vendor/arise/numbers/lib/libaudsd2pcm.so:system/lib/libaudsd2pcm.so \
    vendor/arise/numbers/lib/libauaudioutils.so:system/lib/libauaudioutils.so \
    vendor/arise/numbers/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so:system/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so \
    vendor/arise/numbers/lib/libambisonic_audio_renderer.so:system/lib/libambisonic_audio_renderer.so \
    vendor/arise/numbers/lib/libaemagic.so:system/lib/libaemagic.so \
    vendor/arise/numbers/etc/srs/srs_processing.cfg:system/etc/srs/srs_processing.cfg \
    vendor/arise/numbers/etc/srs/srsmodels.lic:system/etc/srs/srsmodels.lic \
    vendor/arise/numbers/etc/srs/models.txt:system/etc/srs/models.txt \
    vendor/arise/numbers/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
    vendor/arise/numbers/etc/dts/tuning_configs:system/etc/dts/tuning_configs \
    vendor/arise/numbers/etc/dts/srs_processing_vocal.cfg:system/etc/dts/srs_processing_vocal.cfg \
    vendor/arise/numbers/etc/dts/srs_processing_off.cfg:system/etc/dts/srs_processing_off.cfg \
    vendor/arise/numbers/etc/dts/srs_processing_music.cfg:system/etc/dts/srs_processing_music.cfg \
    vendor/arise/numbers/etc/dts/srs_processing_movie.cfg:system/etc/dts/srs_processing_movie.cfg \
    vendor/arise/numbers/etc/dts/srs_processing_gaming.cfg:system/etc/dts/srs_processing_gaming.cfg \
    vendor/arise/numbers/etc/dts/speaker_off:system/etc/dts/speaker_off \
    vendor/arise/numbers/etc/dts/speaker_4:system/etc/dts/speaker_4 \
    vendor/arise/numbers/etc/dts/speaker_3:system/etc/dts/speaker_3 \
    vendor/arise/numbers/etc/dts/speaker_2:system/etc/dts/speaker_2 \
    vendor/arise/numbers/etc/dts/speaker_1:system/etc/dts/speaker_1 \
    vendor/arise/numbers/etc/dts/speaker_0:system/etc/dts/speaker_0 \
    vendor/arise/numbers/etc/dts/other.dtscs:system/etc/dts/other.dtscs \
    vendor/arise/numbers/etc/dts/m6-lic.key:system/etc/dts/m6-lic.key \
    vendor/arise/numbers/etc/dts/lineout_9:system/etc/dts/lineout_9 \
    vendor/arise/numbers/etc/dts/lineout_8:system/etc/dts/lineout_8 \
    vendor/arise/numbers/etc/dts/lineout_7:system/etc/dts/lineout_7 \
    vendor/arise/numbers/etc/dts/lineout_6:system/etc/dts/lineout_6 \
    vendor/arise/numbers/etc/dts/lineout_5:system/etc/dts/lineout_5 \
    vendor/arise/numbers/etc/dts/lineout_4:system/etc/dts/lineout_4 \
    vendor/arise/numbers/etc/dts/lineout_3:system/etc/dts/lineout_3 \
    vendor/arise/numbers/etc/dts/lineout_2:system/etc/dts/lineout_2 \
    vendor/arise/numbers/etc/dts/lineout_1:system/etc/dts/lineout_1 \
    vendor/arise/numbers/etc/dts/lineout_0:system/etc/dts/lineout_0 \
    vendor/arise/numbers/etc/dts/lineout0.dtscs:system/etc/dts/lineout0.dtscs \
    vendor/arise/numbers/etc/dts/eagle-lic.key:system/etc/dts/eagle-lic.key \
    vendor/arise/numbers/etc/dts/dts-m6m8-lic.key:system/etc/dts/dts-m6m8-lic.key \
    vendor/arise/numbers/etc/dts/dts-eagle.lic:system/etc/dts/dts-eagle.lic \
    vendor/arise/numbers/etc/dts/dts.lic:system/etc/dts/dts.lic \
    vendor/arise/numbers/etc/dts/configurator.cfg:system/etc/dts/configurator.cfg \
    vendor/arise/numbers/etc/dts/combo0.dtscs:system/etc/dts/combo0.dtscs \
    vendor/arise/numbers/etc/dts/bluetooth_4:system/etc/dts/bluetooth_4 \
    vendor/arise/numbers/etc/dts/bluetooth_3:system/etc/dts/bluetooth_3 \
    vendor/arise/numbers/etc/dts/bluetooth_2:system/etc/dts/bluetooth_2 \
    vendor/arise/numbers/etc/dts/bluetooth_1:system/etc/dts/bluetooth_1 \
    vendor/arise/numbers/etc/dts/bluetooth_0:system/etc/dts/bluetooth_0 \
    vendor/arise/numbers/etc/dts/bluetooth0.dtscs:system/etc/dts/bluetooth0.dtscs \
    vendor/arise/numbers/etc/dts/attached1.dtscs:system/etc/dts/attached1.dtscs \
    vendor/arise/numbers/etc/dolby/dax-default.xml:system/etc/dolby/dax-default.xml \
    vendor/arise/numbers/etc/audio/dts/dts_VIENNA_normal.xml:system/etc/audio/dts/dts_VIENNA_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_PLK_UL_normal.xml:system/etc/audio/dts/dts_PLK_UL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_PLK_TL_normal.xml:system/etc/audio/dts/dts_PLK_TL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_PLK_CL_normal.xml:system/etc/audio/dts/dts_PLK_CL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_PLK_AL_normal.xml:system/etc/audio/dts/dts_PLK_AL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_NEXT_normal.xml:system/etc/audio/dts/dts_NEXT_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_MOZART_normal.xml:system/etc/audio/dts/dts_MOZART_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_LITTLEBOY_normal.xml:system/etc/audio/dts/dts_LITTLEBOY_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_LISZT_normal.xml:system/etc/audio/dts/dts_LISZT_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_KNIGHT_normal.xml:system/etc/audio/dts/dts_KNIGHT_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_KEPLER_normal.xml:system/etc/audio/dts/dts_KEPLER_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_hi3650_normal.xml:system/etc/audio/dts/dts_hi3650_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_hi3635_normal.xml:system/etc/audio/dts/dts_hi3635_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_hi3635cs_normal.xml:system/etc/audio/dts/dts_hi3635cs_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_GRACE_UL_normal.xml:system/etc/audio/dts/dts_GRACE_UL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_GRACE_TUGL_normal.xml:system/etc/audio/dts/dts_GRACE_TUGL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_GRACEES_normal.xml:system/etc/audio/dts/dts_GRACEES_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_GRACE_CLG_normal.xml:system/etc/audio/dts/dts_GRACE_CLG_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_GEMINI_normal.xml:system/etc/audio/dts/dts_GEMINI_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_GALILEO_normal.xml:system/etc/audio/dts/dts_GALILEO_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_FRD_normal.xml:system/etc/audio/dts/dts_FRD_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_EVA_normal.xml:system/etc/audio/dts/dts_EVA_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_EDISON_normal.xml:system/etc/audio/dts/dts_EDISON_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_default.xml:system/etc/audio/dts/dts_default.xml \
    vendor/arise/numbers/etc/audio/dts/dts_DAVINCE_normal.xml:system/etc/audio/dts/dts_DAVINCE_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_DAVINCE_CLG_normal.xml:system/etc/audio/dts/dts_DAVINCE_CLG_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_CARRERA_UL_normal.xml:system/etc/audio/dts/dts_CARRERA_UL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_CARRERA_TUGL_normal.xml:system/etc/audio/dts/dts_CARRERA_TUGL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/dts_CARRERA_CLG_normal.xml:system/etc/audio/dts/dts_CARRERA_CLG_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_SOPHIA_normal.xml:system/etc/audio/dts/ascend_dts_algo_SOPHIA_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_SOPHIACLG_normal.xml:system/etc/audio/dts/ascend_dts_algo_SOPHIACLG_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_OSCARVA_normal.xml:system/etc/audio/dts/ascend_dts_algo_OSCARVA_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_OSCARUL_normal.xml:system/etc/audio/dts/ascend_dts_algo_OSCARUL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_OSCARTL_normal.xml:system/etc/audio/dts/ascend_dts_algo_OSCARTL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_OSCAR_normal.xml:system/etc/audio/dts/ascend_dts_algo_OSCAR_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_HONORUL_normal.xml:system/etc/audio/dts/ascend_dts_algo_HONORUL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_HONORTL_normal.xml:system/etc/audio/dts/ascend_dts_algo_HONORTL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_hi3650_normal.xml:system/etc/audio/dts/ascend_dts_algo_hi3650_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_hi3635_normal.xml:system/etc/audio/dts/ascend_dts_algo_hi3635_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_hi3635cs_normal.xml:system/etc/audio/dts/ascend_dts_algo_hi3635cs_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_GRACE_UL_normal.xml:system/etc/audio/dts/ascend_dts_algo_GRACE_UL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_GRACE_TUGL_normal.xml:system/etc/audio/dts/ascend_dts_algo_GRACE_TUGL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_GRACE_ES_normal.xml:system/etc/audio/dts/ascend_dts_algo_GRACE_ES_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_GRACE_CLG_normal.xml:system/etc/audio/dts/ascend_dts_algo_GRACE_CLG_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_EDGEPUL_normal.xml:system/etc/audio/dts/ascend_dts_algo_EDGEPUL_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_EDGEPUG_normal.xml:system/etc/audio/dts/ascend_dts_algo_EDGEPUG_normal.xml \
    vendor/arise/numbers/etc/audio/dts/ascend_dts_algo_default_normal.xml:system/etc/audio/dts/ascend_dts_algo_default_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_SOPHIA_normal.xml:system/etc/audio/codec/ascend_SOPHIA_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_SOPHIACLG_normal.xml:system/etc/audio/codec/ascend_SOPHIACLG_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_SOPHIACLG_ce.xml:system/etc/audio/codec/ascend_SOPHIACLG_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_SOPHIA_ce.xml:system/etc/audio/codec/ascend_SOPHIA_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCARVA_normal.xml:system/etc/audio/codec/ascend_OSCARVA_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCARVA_ce.xml:system/etc/audio/codec/ascend_OSCARVA_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCARUL_normal.xml:system/etc/audio/codec/ascend_OSCARUL_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCARUL_ce.xml:system/etc/audio/codec/ascend_OSCARUL_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCARTL_normal.xml:system/etc/audio/codec/ascend_OSCARTL_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCARTL_ce.xml:system/etc/audio/codec/ascend_OSCARTL_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCAR_normal.xml:system/etc/audio/codec/ascend_OSCAR_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_OSCAR_ce.xml:system/etc/audio/codec/ascend_OSCAR_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_HONORUL_normal.xml:system/etc/audio/codec/ascend_HONORUL_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_HONORUL_ce.xml:system/etc/audio/codec/ascend_HONORUL_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_HONORTL_normal.xml:system/etc/audio/codec/ascend_HONORTL_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_HONORTL_ce.xml:system/etc/audio/codec/ascend_HONORTL_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_EDGEPUL_normal.xml:system/etc/audio/codec/ascend_EDGEPUL_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_EDGEPUL_ce.xml:system/etc/audio/codec/ascend_EDGEPUL_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_EDGEPUG_normal.xml:system/etc/audio/codec/ascend_EDGEPUG_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_EDGEPUG_ce.xml:system/etc/audio/codec/ascend_EDGEPUG_ce.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_default_normal.xml:system/etc/audio/codec/ascend_default_normal.xml \
    vendor/arise/numbers/etc/audio/codec/ascend_default_ce.xml:system/etc/audio/codec/ascend_default_ce.xml \
    vendor/arise/numbers/etc/audio/algorithm/ascend_algorithm_default.xml:system/etc/audio/algorithm/ascend_algorithm_default.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_VIENNA_normal.xml:system/etc/audio/algorithm/algorithm_VIENNA_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_SOPHIA_normal.xml:system/etc/audio/algorithm/algorithm_SOPHIA_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_SOPHIACLG_normal.xml:system/etc/audio/algorithm/algorithm_SOPHIACLG_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_PLK_UL_normal.xml:system/etc/audio/algorithm/algorithm_PLK_UL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_PLK_TL_normal.xml:system/etc/audio/algorithm/algorithm_PLK_TL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_PLK_CL_normal.xml:system/etc/audio/algorithm/algorithm_PLK_CL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_PLK_AL_normal.xml:system/etc/audio/algorithm/algorithm_PLK_AL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_OSCARVA_normal.xml:system/etc/audio/algorithm/algorithm_OSCARVA_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_OSCARUL_normal.xml:system/etc/audio/algorithm/algorithm_OSCARUL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_OSCARTL_normal.xml:system/etc/audio/algorithm/algorithm_OSCARTL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_OSCAR_normal.xml:system/etc/audio/algorithm/algorithm_OSCAR_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_NEXT_normal.xml:system/etc/audio/algorithm/algorithm_NEXT_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_MOZART_normal.xml:system/etc/audio/algorithm/algorithm_MOZART_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_LITTLEBOY_normal.xml:system/etc/audio/algorithm/algorithm_LITTLEBOY_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_LISZT_normal.xml:system/etc/audio/algorithm/algorithm_LISZT_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_KNIGHT_normal.xml:system/etc/audio/algorithm/algorithm_KNIGHT_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_KEPLER_normal.xml:system/etc/audio/algorithm/algorithm_KEPLER_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_HONORUL_normal.xml:system/etc/audio/algorithm/algorithm_HONORUL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_HONORTL_normal.xml:system/etc/audio/algorithm/algorithm_HONORTL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_hi3650_normal.xml:system/etc/audio/algorithm/algorithm_hi3650_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_hi3635_normal.xml:system/etc/audio/algorithm/algorithm_hi3635_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_hi3635cs_normal.xml:system/etc/audio/algorithm/algorithm_hi3635cs_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_GRACE_UL_normal.xml:system/etc/audio/algorithm/algorithm_GRACE_UL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_GRACE_TUGL_normal.xml:system/etc/audio/algorithm/algorithm_GRACE_TUGL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_GRACEES_normal.xml:system/etc/audio/algorithm/algorithm_GRACEES_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_GRACE_ES_normal.xml:system/etc/audio/algorithm/algorithm_GRACE_ES_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_GRACE_CLG_normal.xml:system/etc/audio/algorithm/algorithm_GRACE_CLG_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_GEMINI_normal.xml:system/etc/audio/algorithm/algorithm_GEMINI_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_GALILEO_normal.xml:system/etc/audio/algorithm/algorithm_GALILEO_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_FRD_normal.xml:system/etc/audio/algorithm/algorithm_FRD_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_EVA_normal.xml:system/etc/audio/algorithm/algorithm_EVA_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_EDISON_normal.xml:system/etc/audio/algorithm/algorithm_EDISON_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_EDGEPUL_normal.xml:system/etc/audio/algorithm/algorithm_EDGEPUL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_EDGEPUG_normal.xml:system/etc/audio/algorithm/algorithm_EDGEPUG_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_default_normal.xml:system/etc/audio/algorithm/algorithm_default_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_DAVINCE_normal.xml:system/etc/audio/algorithm/algorithm_DAVINCE_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_DAVINCE_CLG_normal.xml:system/etc/audio/algorithm/algorithm_DAVINCE_CLG_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_CARRERA_UL_normal.xml:system/etc/audio/algorithm/algorithm_CARRERA_UL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_CARRERA_TUGL_normal.xml:system/etc/audio/algorithm/algorithm_CARRERA_TUGL_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_CARRERA_CLG_normal.xml:system/etc/audio/algorithm/algorithm_CARRERA_CLG_normal.xml \
    vendor/arise/numbers/etc/audio/algorithm/algorithm_BEETHOVEN_normal.xml:system/etc/audio/algorithm/algorithm_BEETHOVEN_normal.xml \
    vendor/arise/numbers/etc/icesoundpresets.def:system/etc/icesoundpresets.def \
    vendor/arise/numbers/etc/icesoundconfig.def:system/etc/icesoundconfig.def \
    vendor/arise/numbers/etc/dts-eagle.lic:system/etc/dts-eagle.lic \
    vendor/arise/numbers/etc/dts-decoder.lic:system/etc/dts-decoder.lic \
    vendor/arise/numbers/etc/audio_effects.conf:system/etc/audio_effects.conf \
    vendor/arise/numbers/bin/dts_v:system/bin/dts_v \
    vendor/arise/numbers/bin/dts_hpx_service:system/bin/dts_hpx_service \
    vendor/arise/numbers/bin/dts_configurator:system/bin/dts_configurator \
    vendor/arise/numbers/ARISE_Version.prop:system/ARISE_Version.prop \
    vendor/arise/customize/app/x86/libV4AJniUtils.so:system/priv-app/ViPER4Arise/x86/libV4AJniUtils.so \
    vendor/arise/customize/app/armeabi/libV4AJniUtils.so:system/priv-app/ViPER4Arise/armeabi/libV4AJniUtils.so
    

PRODUCT_PACKAGES += ViPER4Arise
