#!/system/bin/sh

LOG_FILE=/data/local/tp_run.log;

##                                      ##
##           EPHEXXIS SET PROP          ##
##                                      ##
##            XDA Developers            ##
##                                      ##


## Audio Offload ##

#
setprop audio.offload.disable 0
setprop audio.offload.pcm.enable true
setprop audio.offload.pcm.16bit.enable true
setprop audio.offload.pcm.24bit.enable true
#Minimum duration for offload playback in secs
setprop audio.offload.min.duration.secs 20
#setprop audio.offload.video true
setprop audio.offload.track.enable true
setprop audio.offload.gapless.enabled true
setprop audio.offload.passthrough true
setprop audio.offload.multiple.enabled true
setprop audio.offload.multiaac.enable true
#
setprop audio.deep_buffer.media true
setprop lpa.deepbuffer.enable 1
setprop lpa.releaselock true
setprop lpa.decode true
setprop lpa.use-stagefright true
setprop tunnel.decode false
setprop tunnel.audio.encode true
setprop audio.safx.pbe.enabled true
setprop mm.enable.smoothstreaming true
setprop ro.lge.audio_soundexception true
#
setprop widi.media.extmode.enable 1
setprop persist.hwc.mdpcomp.enable true
#letv2 Dolby effects.#
setprop dolby.audio.sink.info headphone
setprop dolby.ds.dialogenhancer.state off
setprop dolby.ds.graphiceq.state off
setprop dolby.ds.intelligenteq.preset ieq_open
setprop dolby.ds.intelligenteq.state on
setprop dolby.ds.profile.name Music
setprop dolby.ds.state on
setprop dolby.ds.virt.bluetooth off
setprop dolby.ds.virt.hdmi off
setprop dolby.ds.virt.headphone_port on
setprop dolby.ds.virt.internal_speaker off
setprop dolby.ds.virt.miracast off
setprop dolby.ds.virt.usb on
setprop dolby.ds.volumeleveler.state off
setprop dolby.monospeaker false
#codecs:(PARSER_)AAC AC3 AMR_NB AMR_WB ASF AVI DTS FLV 3GP 3G2 MKV MP2PS MP2TS MP3 OGG QCP WAV FLAC AIFF APE
setprop mm.enable.qcom_parser 1048575
setprop persist.mm.enable.prefetch true
setprop qcom.hw.aac.encoder true

#
# System props for DOLBY+
setprop dmid=3067269873
setprop audio.ds1.metainfo.key=273
setprop audio.dolby.ds1.enabled true
setprop audio.dolby.ds1.hardbypass true
setprop audio.dolby.ds2.enabled true
setprop audio.dolby.ds2.hardbypass true
setprop audio.dolby.dax.enabled true
setprop audio.dolby.dax.hardbypass true

#lines to make pulse work uncheck if you need them I've had reports that it now worker without them but I'll leave them here for now just incase  #
setprop ro.semc.sound_effects_enabled true
setprop ro.semc.enhance.supported true
setprop ro.somc.clearphase.supported true
setprop ro.semc.clearaudio.supported true
setprop ro.semc.xloud.supported true
setprop persist.service.enhance.enable 1
setprop persist.service.clearphase.enable 1
setprop persist.service.clearaudio.enable 1
setprop persist.service.xloud.enable 1
setprop com.sonymobile.clearphase_enabled true
setprop com.sonyericsson.xloud_enabled true
setprop ro.semc.enhance.supported true
setprop ro.semc.sound_effects_enabled true
#setprop ro.somc.cp.default_setting true

# MAXXAUDIO 
setprop audiofx.global.enable 1
setprop audiofx.global.dts.enable 1
setprop audiofx.eq.preset 6
setprop audiofx.bass.enable 1
setprop audiofx.bass.strength 55
setprop audiofx.treble.enable 1
setprop audiofx.treble.strength 60
setprop audiofx.virtualizer.enable 1 
setprop audiofx.virtualizer.strength 40 
setprop audiofx.maxxvolume.enable 0

## Asus™ ZenPad 8 Audio ##
#
setprop bluetooth.hfp.client 1
## AudioWizard
setprop ro.asus.audio.feature ar101
setprop ro.asus.audiowizard.config 1

## Vivo™ XPlay 3S Audio ##
#
setprop persist.vivo.phone.hifi Have_hifi
#
## Huawei™ P9 Audio ##
#
setprop ro.config.hw_dts true
setprop use.dts_m6 true
setprop use.dts_m6_notify true
setprop use.dts_eagle true

#SONY effect
setprop sony.support.effect 0x1FF
#  Allocate bit for each effect.
#  If necessary, define effect list with logical sum.
#  EFFECT_DN        0x0001 (Dynamic Normalizer)
#  EFFECT_SF        0x0002 (S-Force)
#  EFFECT_CPHP      0x0004 (ClearPhase Headphone)
#  EFFECT_CA        0x0008 (ClearAudio)
#  EFFECT_VPT       0x0010 (VPT)
#  EFFECT_CPSP      0x0020 (ClearPhase Speaker)
#  EFFECT_XLOUD     0x0040 (xLOUD)
#  EFFECT_CAPLUS    0x0080 (ClearAudio+)
#  EFFECT_SPBUNDLE  0x0100 (Speaker Bundle)
#  EFFECT_ALC       0x0200 (ALC)

# Effect used by Speaker Bundle.
# EFFECT_SF | EFFECT_CPSP | EFFECT_SPBUNDLE   0x122
setprop sony.effect.custom.sp_bundle 0x122

# Effect used by ClearAudio+ headset
# EFFECT_CA | EFFECT_VPT | EFFECT_CAPLUS | EFFECT_ALC   0x298
setprop sony.effect.custom.caplus_hs 0x298

# Effect used by ClearAudio+ speaker
# EFFECT_CA | EFFECT_VPT | EFFECT_CPSP | EFFECT_CAPLUS | EFFECT_ALC   0x2B8
setprop sony.effect.custom.caplus_sp 0x2B8

# LDAC audio support
setprop ro.somc.ldac.audio.supported true
# Force LDAC to run in Bluetooth
setprop persist.service.ldac.enable 1
setprop com.sonymobile.ldac_enabled true

## Miscellaneous Audio ##

setprop sys.keep_app_1 com.atmos
## Enable PowerAmp Hi-Res option ##
setprop ro.lenovo.hifi_support true
setprop ro.service.swiqi2.supported false
setprop persist.service.swiqi2.enable 0

#enable dirac
#setprop ro.dirac.config 16
#setprop ro.dirac.afm.mode global
#setprop ro.dirac.acs.controller afm
#
## htc audio enhancement ##
setprop htc.audio.global.state 1
#profiles: 0 = external speakers, 1 = Headphones, there are others i can't remember
setprop htc.audio.global.profile 0
setprop htc.audio.q6.topology 1
setprop htc.audio.global.speaker 1
setprop htc.audio.beats.state 1
setprop htc.audio.beats.config 1
setprop htc.audio.beats.support2v 1
setprop htc.audio.lpa.a2dp 1
setprop htc.audio.alc.enable 1
# Choose one of the three options below:
#htc.audio.effect.dolby 1
#setprop htc.audio.effect.jbl 4
#htc.audio.effect.harman -1
setprop htc.audio.effect.srs 1

#
## Lenovo™ K4 Note Dolby™ Audio #
#
setprop LENOVO_DOLBY_SUPPORT yes
setprop ro.mtk_dolby_dap_support 1
#
setprop ro.lenovo.soundeffect maxxaudio
## Newskool Dolby FX #
#
setprop ro.mtk_audenh_support 1
setprop ro.mtk_bessurround_support 1
setprop ro.mtk_bt_support 1
setprop ro.mtk_audio_tuning_tool_ver V2.2
setprop ro.have_aacencode_feature 1

##EPHEXXIS##

## Advanced Linux Sound Architecture ##
#
setprop AUDIODRIVER ALSA
setprop alsa.mixer.defaultGain 1.25
#
setprop persist.audio.vr.enable true
setprop mpq.audio.decode 1
setprop media.stagefright.use-awesome true
setprop persist.sys.media.use-awesome true

if [ -e /data/local/tp_run.log ]; then
    rm /data/local/tp_run.log
fi
echo "TweakProp script has run successfully $(date +"%m-%d-%Y %H:%M:%S")" | tee -a $LOG_FILE;
